### ISSUE TITLE
Creating EA-LA mapping pipeline

### ISSUE THREAD

**Issue by Hamedhm** [mpi2/impc-etl#238]
The purpose of this ticket is to keep track of EA-LA mapping pipeline.

@ficolo Generated a file named `early_vs_late_stats_metadta_group.csv` some time ago for the WG, however, for each row, we need two extra columns in the spreadsheet. One for the EA animals ids (`specimen_id`) and the other one for LA animal ids for the animals that the corresponding test in the row are performed on. Both columns should be attached to the very right of the spreadsheet if possible. 

The ids should be comma-separated in the cells like the example below:

![image.png](https://images.zenhubusercontent.com/5e274374043031652fa3a90b/380e3a75-1808-49d5-b796-9afed1784fec)

**Comment by rwilson-ebi** [comment]
No longer needed
