### ISSUE TITLE
[IMPC Web API] Generate the supporting data for the different IMPC API microservices from the ETL

### ISSUE THREAD

**Issue by ficolo** [mpi2/impc-etl#241]
- [x] Gene Summary Service
- [x] Gene Phenotype Hits Service
- [x] Gene Stats results service
- [x] Gene Gauges averages JSON file
- [x] Gene Expression data service
- [x] Gene Images Service
- [x] Gene Diseases Service
- [x] Gene Publications service
- [x] Gene Order Service
- [ ] Allele Products Service

**Comment by rwilson-ebi** [comment]
Closed this ticket as a separate ticket exists to describe the work to produce data on the allele products
