### ISSUE TITLE
Load media observations

### ISSUE THREAD

**Issue by ficolo** [mpi2/impc-etl#6]
The ETL process has to support the loading of media observations from the DCC XML files:

- XML tag name: mediaParameter
- XML value attribute name: URI

Media observations are _mediaParameter_ entries on the XML that contain an URI attribute and a fileType attribute.

**Comment by jmason-ebi** [comment]
Will this also load in the seriesMediaParameter observations, or would you prefer another issue for that?

**Comment by ficolo** [comment]
Will open a new issue for those, so we have separated functions handling them
