### ISSUE TITLE
Load output from ETL process into database and solr

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/impc-etl#87]
The out put from the ETL process is a parquet file.  This needs to be loaded into the solr cores.

**Comment by ficolo** [comment]
- [ ] allele
- [ ] allele2
- [ ] anatomy
- [ ] autosuggest
- [ ] experiment
- [ ] gene
- [ ] genotype-phenotype
- [ ] images
- [ ] impc-images
- [ ] mgi-phenotype
- [ ] mp
- [ ] phenodigm
- [ ] pipeline
- [ ] product
- [ ] statistical-result
