### ISSUE TITLE
Generate ontology annotations from stats results and other sources

### ISSUE THREAD

**Issue by ficolo** [mpi2/impc-etl#90]
Should mimic the logic in:

https://github.com/mpi2/PhenotypeData/blob/master/loads/src/main/java/org/mousephenotype/cda/loads/annotations/OntologyAnnotationGenerator.java

**Comment by jmason-ebi** [comment]
The histopath results need to by updated to use the JSON file and update directly into the solr core.

**Comment by jmason-ebi** [comment]
This needs to include the viability calls and the embryo calls as well.

**Comment by jmason-ebi** [comment]
Also includes 3I calls
